from sm_common.integrations.canonical_types import (
    AppointmentCreated,
    AppointmentRescheduled,
    AppointmentCancelled,
    AppointmentWrite,
    VisitCheckedIn,
    VisitConsultationStarted,
    VisitFinalized,
    CanonicalPatient,
    CanonicalDoctor,
    CanonicalAppointment,
    WriteBackResult,
    CancelResult,
    AdapterHealth,
    ExternalBooking,
    PatientCreate,
    PatientCreateResult,
)
from sm_common.integrations.hms_adapter import HmsAdapter
from sm_common.integrations.exceptions import (
    HmsAdapterError,
    ConflictError,
    TransientError,
    AuthError,
    WriteNotSupported,
    VendorRejected,
    SearchNotSupported,
)

__all__ = [
    "HmsAdapter",
    "AppointmentCreated",
    "AppointmentRescheduled",
    "AppointmentCancelled",
    "AppointmentWrite",
    "VisitCheckedIn",
    "VisitConsultationStarted",
    "VisitFinalized",
    "CanonicalPatient",
    "CanonicalDoctor",
    "CanonicalAppointment",
    "WriteBackResult",
    "CancelResult",
    "AdapterHealth",
    "ExternalBooking",
    "PatientCreate",
    "PatientCreateResult",
    "HmsAdapterError",
    "ConflictError",
    "TransientError",
    "AuthError",
    "WriteNotSupported",
    "VendorRejected",
    "SearchNotSupported",
]
